FEATURE_LABELS = {
    "rating": "Review Rating",
    "restaurantRating": "Business Average Rating",
    "rating_deviation": "Rating Difference",
    "friendCount": "Reviewer Friend Count",
    "reviewCount": "Total Reviews Written",
    "reviewUsefulCount": "Useful Votes on Review",
    "usefulCount": "Total Useful Votes",
    "coolCount": "Total Cool Votes",
    "funnyCount": "Total Funny Votes",
    "complimentCount": "Compliments Received",
    "tipCount": "Tips Written",
    "fanCount": "Fan Count",
    "reviewer_account_age_days": "Account Age in Days",
    "reviewer_engagement_ratio": "Engagement per Review",
    "reviewer_social_reach": "Social Reach Score",
    "reviewer_helpfulness_ratio": "Helpfulness per Review",
    "reviewer_activity_level": "Reviewer Activity Level",
    "review_word_count": "Review Word Count",
}

FEATURE_EXPLANATIONS = {
    "rating": "The star rating given in this review.",
    "restaurantRating": "The average rating of the restaurant or business.",
    "rating_deviation": "Difference between review rating and business average rating.",
    "friendCount": "Number of friends or connections the reviewer has.",
    "reviewCount": "Total number of reviews written by the reviewer.",
    "reviewUsefulCount": "Useful votes received by this specific review.",
    "usefulCount": "Total useful votes received across reviews.",
    "coolCount": "Total cool votes received by the reviewer.",
    "funnyCount": "Total funny votes received by the reviewer.",
    "complimentCount": "Total compliments received by the reviewer.",
    "tipCount": "Number of tips written by the reviewer.",
    "fanCount": "Number of users following this reviewer.",
    "reviewer_account_age_days": "Age of the reviewer account.",
    "reviewer_engagement_ratio": "Average engagement received per review.",
    "reviewer_social_reach": "Combined signal based on friends and fans.",
    "reviewer_helpfulness_ratio": "Average useful votes received per review.",
    "reviewer_activity_level": "Log-based reviewer activity score.",
    "review_word_count": "Approximate number of words in the review.",
}

FEATURE_CATEGORIES = {
    "rating": "Review Context",
    "restaurantRating": "Review Context",
    "rating_deviation": "Review Context",
    "review_word_count": "Review Context",
    "friendCount": "Social Reputation",
    "fanCount": "Social Reputation",
    "reviewer_social_reach": "Social Reputation",
    "reviewCount": "Reviewer History",
    "tipCount": "Reviewer History",
    "reviewer_account_age_days": "Reviewer History",
    "reviewer_activity_level": "Reviewer History",
    "reviewUsefulCount": "Engagement Quality",
    "usefulCount": "Engagement Quality",
    "coolCount": "Engagement Quality",
    "funnyCount": "Engagement Quality",
    "complimentCount": "Engagement Quality",
    "reviewer_engagement_ratio": "Engagement Quality",
    "reviewer_helpfulness_ratio": "Engagement Quality",
}

CATEGORY_DESCRIPTIONS = {
    "Review Context": "Rating behavior and review-level characteristics.",
    "Social Reputation": "Reviewer social footprint and visible community trust.",
    "Reviewer History": "Account longevity, activity history, and reviewer maturity.",
    "Engagement Quality": "Signals from useful votes, compliments, and past review engagement.",
}

PLAIN_ENGLISH_SIGNALS = {
    "rating": "The submitted star rating influenced the case assessment.",
    "restaurantRating": "The business average rating gave context to the review rating.",
    "rating_deviation": "The review rating differs from the business's typical rating pattern.",
    "friendCount": "The reviewer social network size affected the trust signal.",
    "reviewCount": "The reviewer history volume affected the reputation signal.",
    "reviewUsefulCount": "The helpfulness of this specific review affected the evidence profile.",
    "usefulCount": "The reviewer's total useful-vote history affected credibility.",
    "coolCount": "The reviewer's historical engagement profile affected credibility.",
    "funnyCount": "The reviewer's historical interaction profile affected credibility.",
    "complimentCount": "The reviewer's compliment history affected trustworthiness.",
    "tipCount": "The reviewer's tip-writing behavior affected activity context.",
    "fanCount": "The reviewer follower count affected social credibility.",
    "reviewer_account_age_days": "The account age affected reviewer trust context.",
    "reviewer_engagement_ratio": "The engagement per review affected behavioral credibility.",
    "reviewer_social_reach": "The combined friends-and-fans signal affected reviewer reputation.",
    "reviewer_helpfulness_ratio": "The helpfulness per review affected reliability context.",
    "reviewer_activity_level": "The reviewer activity pattern affected the behavioral profile.",
    "review_word_count": "The review length affected content-context strength.",
}
